# Generated by Django 4.1.2 on 2022-10-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_date_posted_item_date_listed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_listed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
