# Generated by Django 4.1.2 on 2022-10-26 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_alter_item_date_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_listed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
