# Generated by Django 4.1.2 on 2022-11-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='item',
            new_name='curr_item',
        ),
    ]
