# Generated by Django 4.1.2 on 2022-11-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_rename_item_bid_curr_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-amount']},
        ),
    ]
