# Generated by Django 4.1.2 on 2022-11-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_bid_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='highest_bid_user',
            field=models.CharField(default='Creator', max_length=256),
        ),
    ]
