# Generated by Django 4.1.2 on 2022-11-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='var/www/media/static/Auction/images'),
        ),
    ]
